# Generated by Django 5.0.6 on 2024-06-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Image',
            field=models.ImageField(upload_to='Media/Items/'),
        ),
    ]
